### ISSUE TITLE
Problems with UTF-8 files

### ISSUE THREAD

**Issue by scarysandwich** [fenhl/lazyjson#2]
The library can't handle files with utf-8 encoding.

      Traceback (most recent call last):
        File "<stdin>", line 1, in <module>
        File ".\common\lazyjson.py", line 76, in __str__
          return str(self.value())
        File ".\common\lazyjson.py", line 90, in value
          return self.root.value_at_key_path(self.key_path)
        File ".\common\lazyjson.py", line 139, in value_at_key_path
          ret = self.value()
        File ".\common\lazyjson.py", line 170, in value
          return json.load(self.file_info)
        File "C:\Python34\lib\json\__init__.py", line 268, in load
          parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
        File "C:\Python34\lib\json\__init__.py", line 318, in loads
          return _default_decoder.decode(s)
        File "C:\Python34\lib\json\decoder.py", line 343, in decode
          obj, end = self.raw_decode(s, idx=_w(s, 0).end())
        File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
          raise ValueError(errmsg("Expecting value", s, err.value)) from None
      ValueError: Expecting value: line 1 column 1 (char 0)

So when i open a file like this:

       fh = codecs.open("C:\data.json", mode="r", encoding="utf-8")

And I try to read it like this:

      datasheets = lazyjson.File(fh, True)
      print(datasheets[0])

I get the exception above.

**Comment by fenhl** [comment]
Fixed in da987d77702fd2fb878f2420f1bd6395caef08a6.
